name: Airflow reusable workflow

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      DOCKERFILE_LOCATION:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT:
        required: true
jobs:
  build:
    runs-on: self-hosted
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sport Definition
        run: |
          echo SPORT=$(echo $GITHUB_JOB|cut -d'-' -f2) >> $GITHUB_ENV
      - name: check env vars
        run: echo $GITHUB_ENV
      - name: Tag definition
        run: |
          if [[ $GITHUB_REF_NAME == 'master' ]] || [[ $GITHUB_REF_NAME == 'main' ]];
            then echo TAG="$SPORT-v2-latest" >> $GITHUB_ENV
          else
            echo TAG="$SPORT-$GITHUB_RUN_ID" >> $GITHUB_ENV
          fi
      - name: Build/publish image to ECR
        uses: nicolasdonoso/build-action@v1.6.6
