name: Airflow reusable workflow

on:
  workflow_call:
  
jobs:
  build:
    runs-on: self-hosted
    environment: build
    env:
      AWS_ACCOUNT: ${{ secrets.PRIMARY_AWS_ACCOUNT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tag definition
        run: |
          if [[ $GITHUB_REF_NAME == 'master' ]] || [[ $GITHUB_REF_NAME == 'main' ]];
            then echo TAG="latest" >> $GITHUB_ENV
          else
            echo TAG="$GITHUB_RUN_ID" >> $GITHUB_ENV
          fi
      - name: Build/publish image to ECR
        uses: nicolasdonoso/build-action@v1.7
  dev:
    runs-on: self-hosted
    environment: $GITHUB_WORKFLOW
    needs: build
    env:
      AWS_ACCOUNT: ${{ secrets.PRIMARY_AWS_ACCOUNT }}
      K8S_KUBECONFIG: ${{ secrets.AWS_ENG_DEV_KUBECONFIG }}
      K8S_CLUSTER: ${{ secrets.ENG_DEV_CLUSTER }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Vars defintion
        run: |
          echo CI_JOB_STAGE=$(echo $GITHUB_JOB|cut -d'-' -f1) >> $GITHUB_ENV
          echo LEAGUE=-$(echo $GITHUB_JOB|cut -d'-' -f2) >> $GITHUB_ENV
          echo NAME=$(echo ${{ github.repository }}|sed 's/_/-/g'|cut -d '/' -f2) >> $GITHUB_ENV
          echo CI_PROJECT_NAME=$(echo ${{ github.repository }}|cut -d '/' -f2) >> $GITHUB_ENV
          echo CI_JOB_STAGE=$(echo $GITHUB_JOB|cut -d'-' -f1) >> $GITHUB_ENV
      - name: Deploy from config
        uses: nicolasdonoso/config-handler@v1.0